/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoed2;

import Cliente.ClienteFacade;
import Cliente.ClienteVO;
import Funcionario.Funcionario;
import Funcionario.GerenciamentoFuncionario;
import java.awt.CardLayout;
import java.awt.Frame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Raíssa Regis
 */
public class Home extends javax.swing.JFrame {

    int x, y;
    CardLayout cardLayout;
    JOptionPane jp = new JOptionPane();
    ClienteFacade clientes = new ClienteFacade();

    public Home() {
        
        initComponents();

        comeco(labelCC, labelCF, labelG, labelL);

        cardLayout = (CardLayout) (CardsMenu.getLayout());

        DefaultTableModel tabela1 = (DefaultTableModel) tabelaContas.getModel();

        tabelaContas.setRowSorter(new TableRowSorter(tabela1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane2 = new javax.swing.JSplitPane();
        MenuEsq = new javax.swing.JPanel();
        jCC = new javax.swing.JButton();
        jCF = new javax.swing.JButton();
        jG = new javax.swing.JButton();
        jAlocacao = new javax.swing.JButton();
        labelG = new javax.swing.JLabel();
        labelL = new javax.swing.JLabel();
        labelCC = new javax.swing.JLabel();
        labelCF = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CardsMenu = new javax.swing.JPanel();
        MainMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CardAloca = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CardCC = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCCNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCCRg = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jCCEndereco = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCCCidade = new javax.swing.JTextField();
        jCCBairro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCCUf = new javax.swing.JTextField();
        jCCButton = new javax.swing.JButton();
        jCCCpf = new javax.swing.JFormattedTextField();
        CardCF = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jCFBairro = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jCFEndereco = new javax.swing.JTextField();
        jCFRg = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jCFNome = new javax.swing.JTextField();
        JCFUf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jCFCpf = new javax.swing.JFormattedTextField();
        jCFButton = new javax.swing.JButton();
        jCFSalario = new javax.swing.JFormattedTextField();
        CardG = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaContas = new javax.swing.JTable();
        opcaoFuncionario = new javax.swing.JRadioButton();
        opcaoCliente = new javax.swing.JRadioButton();
        jAlterarContas = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonConsultarContas = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jNomeAlterar = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jConsultaContas1 = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jAlterarCPF = new javax.swing.JFormattedTextField();
        jTopo = new javax.swing.JPanel();
        exitar = new javax.swing.JLabel();
        maxir = new javax.swing.JLabel();
        minir = new javax.swing.JLabel();
        jIconMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(107, 110, 119));
        setUndecorated(true);
        setResizable(false);

        jSplitPane2.setDividerSize(0);

        MenuEsq.setBackground(new java.awt.Color(57, 57, 57));
        MenuEsq.setMaximumSize(new java.awt.Dimension(220, 195));
        MenuEsq.setMinimumSize(new java.awt.Dimension(220, 195));
        MenuEsq.setPreferredSize(new java.awt.Dimension(220, 195));
        MenuEsq.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCC.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jCC.setForeground(new java.awt.Color(255, 255, 255));
        jCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/padrao2.png"))); // NOI18N
        jCC.setText("Cadastro Cliente");
        jCC.setBorderPainted(false);
        jCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCC.setPreferredSize(new java.awt.Dimension(200, 45));
        jCC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/novosele.png"))); // NOI18N
        jCC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/hover.png"))); // NOI18N
        jCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCActionPerformed(evt);
            }
        });
        MenuEsq.add(jCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, -1));

        jCF.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jCF.setForeground(new java.awt.Color(255, 255, 255));
        jCF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/padrao2.png"))); // NOI18N
        jCF.setText("Cadastro Funcionário");
        jCF.setBorderPainted(false);
        jCF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCF.setPreferredSize(new java.awt.Dimension(200, 45));
        jCF.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/novosele.png"))); // NOI18N
        jCF.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/hover.png"))); // NOI18N
        jCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFActionPerformed(evt);
            }
        });
        MenuEsq.add(jCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 40));

        jG.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jG.setForeground(new java.awt.Color(255, 255, 255));
        jG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/padrao2.png"))); // NOI18N
        jG.setText("Gerenciar Contas");
        jG.setBorderPainted(false);
        jG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jG.setPreferredSize(new java.awt.Dimension(200, 45));
        jG.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/novosele.png"))); // NOI18N
        jG.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/hover.png"))); // NOI18N
        jG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGActionPerformed(evt);
            }
        });
        MenuEsq.add(jG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jAlocacao.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jAlocacao.setForeground(new java.awt.Color(255, 255, 255));
        jAlocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/padrao2.png"))); // NOI18N
        jAlocacao.setText("Alocação");
        jAlocacao.setBorderPainted(false);
        jAlocacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jAlocacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jAlocacao.setPreferredSize(new java.awt.Dimension(200, 45));
        jAlocacao.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/novosele.png"))); // NOI18N
        jAlocacao.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/hover.png"))); // NOI18N
        jAlocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlocacaoActionPerformed(evt);
            }
        });
        MenuEsq.add(jAlocacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        jAlocacao.getAccessibleContext().setAccessibleName("cardAlocacao");

        labelG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/ladooficial.png"))); // NOI18N
        MenuEsq.add(labelG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 10, -1));

        labelL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/ladooficial.png"))); // NOI18N
        MenuEsq.add(labelL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 10, -1));

        labelCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/ladooficial.png"))); // NOI18N
        MenuEsq.add(labelCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 10, -1));

        labelCF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/ladooficial.png"))); // NOI18N
        MenuEsq.add(labelCF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 10, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carreta");
        MenuEsq.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/carreta.png"))); // NOI18N
        MenuEsq.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 60, 60));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("00.1V");
        MenuEsq.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 40, 20));

        jSplitPane2.setLeftComponent(MenuEsq);

        CardsMenu.setPreferredSize(new java.awt.Dimension(823, 585));
        CardsMenu.setLayout(new java.awt.CardLayout());

        MainMenu.setBackground(new java.awt.Color(119, 119, 119));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 65)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(57, 57, 57));
        jLabel8.setText("Alocação de Veículos");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("• Cadastro, consulta, exclusão e impressão.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("• Aloque veículos automotores com facilidade.");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("• Gerencie clientes, funcionários e veículos.");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/road.png"))); // NOI18N

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jLabel14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel8)
                .addGap(77, 77, 77)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainMenuLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        CardsMenu.add(MainMenu, "cardMainMenu");

        CardAloca.setBackground(new java.awt.Color(119, 119, 119));
        CardAloca.setPreferredSize(new java.awt.Dimension(823, 585));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/sadface.png"))); // NOI18N

        javax.swing.GroupLayout CardAlocaLayout = new javax.swing.GroupLayout(CardAloca);
        CardAloca.setLayout(CardAlocaLayout);
        CardAlocaLayout.setHorizontalGroup(
            CardAlocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardAlocaLayout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jLabel7)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        CardAlocaLayout.setVerticalGroup(
            CardAlocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardAlocaLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel7)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        CardsMenu.add(CardAloca, "cardAlocacao");

        CardCC.setBackground(new java.awt.Color(119, 119, 119));
        CardCC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        CardCC.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 70, 640, 10));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF");
        CardCC.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 105, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome");
        CardCC.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 105, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 57, 57));
        jLabel5.setText("Dados Pessoais");
        CardCC.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 187, 30));
        CardCC.add(jCCNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 273, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RG");
        CardCC.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 105, -1));

        try {
            jCCRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardCC.add(jCCRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 160, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cidade");
        CardCC.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 105, 20));
        CardCC.add(jCCEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 550, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Endereço");
        CardCC.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 105, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Bairro");
        CardCC.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 105, -1));
        CardCC.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 10));
        CardCC.add(jCCCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 272, -1));
        CardCC.add(jCCBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 160, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("UF");
        CardCC.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 105, -1));

        jCCUf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CardCC.add(jCCUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 37, -1));

        jCCButton.setForeground(new java.awt.Color(255, 255, 255));
        jCCButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/button.png"))); // NOI18N
        jCCButton.setText("Cadastrar");
        jCCButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCCButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCCButton.setPreferredSize(new java.awt.Dimension(110, 25));
        jCCButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/buttonhover.png"))); // NOI18N
        jCCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCButtonActionPerformed(evt);
            }
        });
        CardCC.add(jCCButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, -1, -1));

        try {
            jCCCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardCC.add(jCCCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 159, -1));

        CardsMenu.add(CardCC, "cardCC");

        CardCF.setBackground(new java.awt.Color(119, 119, 119));
        CardCF.setPreferredSize(new java.awt.Dimension(823, 585));
        CardCF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(57, 57, 57));
        jLabel19.setText("Dados Pessoais");
        CardCF.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 187, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        CardCF.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 70, 650, 10));
        CardCF.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, 50, 10));
        CardCF.add(jCFBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 160, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("UF");
        CardCF.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 105, -1));
        CardCF.add(jCFEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 550, -1));

        try {
            jCFRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardCF.add(jCFRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 153, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CPF");
        CardCF.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 105, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Endereço");
        CardCF.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 105, -1));

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Salário");
        CardCF.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 105, -1));
        CardCF.add(jCFNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 273, -1));

        JCFUf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CardCF.add(JCFUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 37, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("RG");
        CardCF.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 105, -1));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Bairro");
        CardCF.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 105, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Nome");
        CardCF.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 105, -1));

        try {
            jCFCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardCF.add(jCFCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 159, -1));

        jCFButton.setForeground(new java.awt.Color(255, 255, 255));
        jCFButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/button.png"))); // NOI18N
        jCFButton.setText("Cadastrar");
        jCFButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCFButton.setPreferredSize(new java.awt.Dimension(110, 25));
        jCFButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/buttonhover.png"))); // NOI18N
        jCFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCFButtonActionPerformed(evt);
            }
        });
        CardCF.add(jCFButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, -1, -1));

        jCFSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        CardCF.add(jCFSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 160, -1));

        CardsMenu.add(CardCF, "cardCF");

        CardG.setBackground(new java.awt.Color(119, 119, 119));
        CardG.setPreferredSize(new java.awt.Dimension(823, 585));
        CardG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Nome", "CPF", "ID", "Bairro", "Sálario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaContas.setGridColor(new java.awt.Color(129, 129, 129));
        jScrollPane1.setViewportView(tabelaContas);

        CardG.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 870, 190));

        buttonGroup1.add(opcaoFuncionario);
        opcaoFuncionario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        opcaoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        opcaoFuncionario.setText("Funcionário");
        CardG.add(opcaoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 142, -1));

        buttonGroup1.add(opcaoCliente);
        opcaoCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        opcaoCliente.setForeground(new java.awt.Color(255, 255, 255));
        opcaoCliente.setText("Cliente");
        CardG.add(opcaoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 142, -1));

        jAlterarContas.setForeground(new java.awt.Color(255, 255, 255));
        jAlterarContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/button.png"))); // NOI18N
        jAlterarContas.setText("Alterar");
        jAlterarContas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jAlterarContas.setPreferredSize(new java.awt.Dimension(110, 25));
        jAlterarContas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/buttonhover.png"))); // NOI18N
        jAlterarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarContasActionPerformed(evt);
            }
        });
        CardG.add(jAlterarContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        jButtonExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/button.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExcluir.setPreferredSize(new java.awt.Dimension(110, 25));
        jButtonExcluir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/buttonhover.png"))); // NOI18N
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        CardG.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jButtonConsultarContas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/button.png"))); // NOI18N
        jButtonConsultarContas.setText("Consultar");
        jButtonConsultarContas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConsultarContas.setPreferredSize(new java.awt.Dimension(110, 25));
        jButtonConsultarContas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/buttonhover.png"))); // NOI18N
        jButtonConsultarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarContasActionPerformed(evt);
            }
        });
        CardG.add(jButtonConsultarContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));
        CardG.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 900, 10));
        CardG.add(jNomeAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 150, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Consulta (CPF)");
        CardG.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 130, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Escolha somente por linha");
        CardG.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 200, 40));

        try {
            jConsultaContas1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardG.add(jConsultaContas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 140, -1));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("CPF");
        CardG.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 130, -1));
        CardG.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 302, 900, 10));

        jLabel32.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Nome");
        CardG.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, -1));

        try {
            jAlterarCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CardG.add(jAlterarCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 140, -1));

        CardsMenu.add(CardG, "cardG");

        jSplitPane2.setRightComponent(CardsMenu);

        jTopo.setBackground(new java.awt.Color(38, 38, 38));
        jTopo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTopoMouseDragged(evt);
            }
        });
        jTopo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTopoMousePressed(evt);
            }
        });

        exitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/sair6.png"))); // NOI18N
        exitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitarMousePressed(evt);
            }
        });

        maxir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/max.png"))); // NOI18N

        minir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/mini.png"))); // NOI18N
        minir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minirMousePressed(evt);
            }
        });

        jIconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/casa7.png"))); // NOI18N
        jIconMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jIconMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jIconMenuMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jTopoLayout = new javax.swing.GroupLayout(jTopo);
        jTopo.setLayout(jTopoLayout);
        jTopoLayout.setHorizontalGroup(
            jTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jIconMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1080, Short.MAX_VALUE)
                .addComponent(minir)
                .addGap(18, 18, 18)
                .addComponent(maxir)
                .addGap(14, 14, 14)
                .addComponent(exitar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jTopoLayout.setVerticalGroup(
            jTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(minir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(maxir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(exitar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jIconMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSplitPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTopo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 629, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 23, Short.MAX_VALUE)
                    .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCActionPerformed
        cardLayout.show(CardsMenu, "cardCC");
        setReset(labelCC, labelG, labelCF, labelL);

    }//GEN-LAST:event_jCCActionPerformed

    private void jCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFActionPerformed
        cardLayout.show(CardsMenu, "cardCF");
        setReset(labelCF, labelG, labelCC, labelL);
    }//GEN-LAST:event_jCFActionPerformed

    private void jGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGActionPerformed
        cardLayout.show(CardsMenu, "cardG");
        setReset(labelG, labelCC, labelCF, labelL);
    }//GEN-LAST:event_jGActionPerformed

    private void jAlocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlocacaoActionPerformed
        cardLayout.show(CardsMenu, "cardAlocacao");
        setReset(labelL, labelG, labelCC, labelCF);
    }//GEN-LAST:event_jAlocacaoActionPerformed

    private void exitarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitarMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitarMousePressed

    private void minirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minirMousePressed
        Home.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minirMousePressed

    private void jTopoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTopoMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jTopoMousePressed

    private void jTopoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTopoMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);

    }//GEN-LAST:event_jTopoMouseDragged

    private void jIconMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconMenuMousePressed
        cardLayout.show(CardsMenu, "cardMainMenu");
        comeco(labelCC, labelCF, labelG, labelL);
    }//GEN-LAST:event_jIconMenuMousePressed

    private void jCCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCButtonActionPerformed
        String nome = jCCNome.getText();
        String cpf = jCCCpf.getText();
        String rg = jCCRg.getText();
        String endereco = jCCEndereco.getText();
        String estado = jCCUf.getText();
        String bairro = jCCBairro.getText();
        String cidade = jCCCidade.getText();

        ClienteVO cliente = new ClienteVO(cpf, rg, nome, endereco, estado, bairro, cidade);

        String tipo = cliente.getTipo();
        int id = cliente.getId();

        clientes.cadastrarCliente(cliente);

        inserirTabelaContas(tipo, nome, cpf, id, bairro);

        jp.showMessageDialog(null, "Cadastro do cliente efetuado com sucesso!", null, JOptionPane.PLAIN_MESSAGE);
        if (jp.isShowing() == false) {
            limparCliente();
        }

    }//GEN-LAST:event_jCCButtonActionPerformed

    private void jCFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCFButtonActionPerformed
        String nome = jCFNome.getText();
        String cpf = jCFCpf.getText();
        String rg = jCFRg.getText();
        String endereco = jCFEndereco.getText();
        String bairro = jCFBairro.getText();
        String estado = JCFUf.getText();
        double salario = Double.parseDouble(jCFSalario.getText());

        Funcionario nv = new Funcionario(cpf, rg, nome, endereco, rg, bairro, salario);
        GerenciamentoFuncionario.incluir(nv);

        int id = nv.getId();
        String tipo = nv.getTipo();

        inserirTabelaContas(tipo, nome, cpf, id, bairro, salario);

        jp.showMessageDialog(null, "Cadastro do funcionário efetuado com sucesso!", null, JOptionPane.PLAIN_MESSAGE);
        if (jp.isShowing() == false) {
            limparFuncionario();
        }


    }//GEN-LAST:event_jCFButtonActionPerformed

    private void jButtonConsultarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarContasActionPerformed
        opcoes();
    }//GEN-LAST:event_jButtonConsultarContasActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        exclusao();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jAlterarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarContasActionPerformed
        alterar();
    }//GEN-LAST:event_jAlterarContasActionPerformed

    public void setReset(JLabel visible, JLabel reset, JLabel reset2, JLabel reset3) {
        visible.setVisible(true);
        reset.setVisible(false);
        reset2.setVisible(false);
        reset3.setVisible(false);
    }

    public void comeco(JLabel reset1, JLabel reset2, JLabel reset3, JLabel reset4) {
        reset1.setVisible(false);
        reset2.setVisible(false);
        reset3.setVisible(false);
        reset4.setVisible(false);
    }

    public void inserirTabelaContas(Object tipo, Object nome, Object cpf, Object id, Object bairro) {
        DefaultTableModel tabela1 = (DefaultTableModel) tabelaContas.getModel();
        Object[] inserir = {tipo, nome, cpf, id, bairro};
        tabela1.addRow(inserir);
    }

    public void inserirTabelaContas(Object tipo, Object nome, Object cpf, Object id, Object bairro, Object salario) {

        DefaultTableModel tabela1 = (DefaultTableModel) tabelaContas.getModel();
        Object[] inserir = {tipo, nome, cpf, id, bairro, salario};
        tabela1.addRow(inserir);
    }

    public void limparFuncionario() {

        jCFNome.setText("");
        jCFCpf.setText("");
        jCFRg.setText("");
        jCFEndereco.setText("");
        jCFBairro.setText("");
        JCFUf.setText("");
        jCFSalario.setText("");
    }

    public void limparCliente() {
        jCCNome.setText("");
        jCCCpf.setText("");
        jCCRg.setText("");
        jCCEndereco.setText("");
        jCCUf.setText("");
        jCCBairro.setText("");
        jCCCidade.setText("");
    }

    public void opcoes() {

        String opcao = jConsultaContas1.getText();

        if (opcaoCliente.isSelected()) {

            if (clientes.consultarCliente(opcao) != -1) {
                
                int i = clientes.consultarCliente(opcao);
                String info = clientes.cliente(i);
                JOptionPane.showMessageDialog(null, info, "Dados", JOptionPane.PLAIN_MESSAGE);
                

            } else {
                JOptionPane.showMessageDialog(null, "Cliente inexistente!", "Dados", JOptionPane.PLAIN_MESSAGE);

            }

        } else if (opcaoFuncionario.isSelected()) {

            if (GerenciamentoFuncionario.consultar(opcao) != -1) {
                
                int i = GerenciamentoFuncionario.consultar(opcao);
                String info = GerenciamentoFuncionario.listar(i);
                JOptionPane.showMessageDialog(null, info, "Dados", JOptionPane.PLAIN_MESSAGE);

            } else {
                
                JOptionPane.showMessageDialog(null, "Funcionário inexistente!", "Dados", JOptionPane.PLAIN_MESSAGE);

            }

        }

    }

    public void exclusao() {
        DefaultTableModel tabela1 = (DefaultTableModel) tabelaContas.getModel();

        if (tabelaContas.getSelectedRow() != -1) {

            int id = (int) tabela1.getValueAt(tabelaContas.getSelectedRow(), 3);

            if (clientes.excluirCliente(id) != -1) {
                clientes.excluirCliente(id);
            } else {
                
                GerenciamentoFuncionario.excluir(id);
            }

            tabela1.removeRow(tabelaContas.getSelectedRow());

        }
    }

    public void alterar() {

        DefaultTableModel tabela1 = (DefaultTableModel) tabelaContas.getModel();

        String novonome = jNomeAlterar.getText();
        String novocpf = jAlterarCPF.getText();
        int id = (int) tabela1.getValueAt(tabelaContas.getSelectedRow(), 3);

        if (GerenciamentoFuncionario.alterar(id) != -1) {

            tabela1.setValueAt(novonome, tabelaContas.getSelectedRow(), 1);
            tabela1.setValueAt(novocpf, tabelaContas.getSelectedRow(), 2);

            int indice = GerenciamentoFuncionario.alterar(id);

            GerenciamentoFuncionario.getLista().get(indice).setNome(novonome);
            GerenciamentoFuncionario.getLista().get(indice).setCpf(novocpf);

        } else {

            tabela1.setValueAt(novonome, tabelaContas.getSelectedRow(), 1);
            tabela1.setValueAt(novocpf, tabelaContas.getSelectedRow(), 2);

            int indice = clientes.alterarCliente(id);

            clientes.getClienteBO().getClienteDAO().getClienteLista().get(indice).setNome(novonome);
            clientes.getClienteBO().getClienteDAO().getClienteLista().get(indice).setCpf(novocpf);
        }
        
        jNomeAlterar.setText("");
        jAlterarCPF.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardAloca;
    private javax.swing.JPanel CardCC;
    private javax.swing.JPanel CardCF;
    private javax.swing.JPanel CardG;
    private javax.swing.JPanel CardsMenu;
    private javax.swing.JTextField JCFUf;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel MenuEsq;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel exitar;
    private javax.swing.JButton jAlocacao;
    private javax.swing.JFormattedTextField jAlterarCPF;
    private javax.swing.JButton jAlterarContas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonConsultarContas;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jCC;
    private javax.swing.JTextField jCCBairro;
    private javax.swing.JButton jCCButton;
    private javax.swing.JTextField jCCCidade;
    private javax.swing.JFormattedTextField jCCCpf;
    private javax.swing.JTextField jCCEndereco;
    private javax.swing.JTextField jCCNome;
    private javax.swing.JFormattedTextField jCCRg;
    private javax.swing.JTextField jCCUf;
    private javax.swing.JButton jCF;
    private javax.swing.JTextField jCFBairro;
    private javax.swing.JButton jCFButton;
    private javax.swing.JFormattedTextField jCFCpf;
    private javax.swing.JTextField jCFEndereco;
    private javax.swing.JTextField jCFNome;
    private javax.swing.JFormattedTextField jCFRg;
    private javax.swing.JFormattedTextField jCFSalario;
    private javax.swing.JFormattedTextField jConsultaContas1;
    private javax.swing.JButton jG;
    private javax.swing.JLabel jIconMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNomeAlterar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel jTopo;
    private javax.swing.JLabel labelCC;
    private javax.swing.JLabel labelCF;
    private javax.swing.JLabel labelG;
    private javax.swing.JLabel labelL;
    private javax.swing.JLabel maxir;
    private javax.swing.JLabel minir;
    private javax.swing.JRadioButton opcaoCliente;
    private javax.swing.JRadioButton opcaoFuncionario;
    private javax.swing.JTable tabelaContas;
    // End of variables declaration//GEN-END:variables
}
