/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoed2;

import java.awt.Frame;

/**
 *
 * @author Raíssa Regis
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form Info
     */
    
    int x, y;
    public Info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTopo1 = new javax.swing.JPanel();
        exitar1 = new javax.swing.JLabel();
        maxir1 = new javax.swing.JLabel();
        minir1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(119, 119, 119));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(119, 119, 119));

        jTopo1.setBackground(new java.awt.Color(38, 38, 38));
        jTopo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTopo1MouseDragged(evt);
            }
        });
        jTopo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTopo1MousePressed(evt);
            }
        });

        exitar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/sair6.png"))); // NOI18N
        exitar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitar1MousePressed(evt);
            }
        });

        maxir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/max.png"))); // NOI18N

        minir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensbotao/mini.png"))); // NOI18N
        minir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minir1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jTopo1Layout = new javax.swing.GroupLayout(jTopo1);
        jTopo1.setLayout(jTopo1Layout);
        jTopo1Layout.setHorizontalGroup(
            jTopo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTopo1Layout.createSequentialGroup()
                .addContainerGap(934, Short.MAX_VALUE)
                .addComponent(minir1)
                .addGap(18, 18, 18)
                .addComponent(maxir1)
                .addGap(14, 14, 14)
                .addComponent(exitar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jTopo1Layout.setVerticalGroup(
            jTopo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTopo1Layout.createSequentialGroup()
                .addGroup(jTopo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(minir1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxir1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTopo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTopo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 558, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitar1MousePressed
        System.exit(0);
    }//GEN-LAST:event_exitar1MousePressed

    private void minir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minir1MousePressed
        Info.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_minir1MousePressed

    private void jTopo1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTopo1MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy -y);

    }//GEN-LAST:event_jTopo1MouseDragged

    private void jTopo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTopo1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jTopo1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitar;
    private javax.swing.JLabel exitar1;
    private javax.swing.JLabel jIconMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jTopo;
    private javax.swing.JPanel jTopo1;
    private javax.swing.JLabel maxir;
    private javax.swing.JLabel maxir1;
    private javax.swing.JLabel minir;
    private javax.swing.JLabel minir1;
    // End of variables declaration//GEN-END:variables
}
